### PR TITLE
[WIP] Convert to Swift 2.1

### PR DESCRIPTION
**Pull request by harlanhaskins**
• Converted all files to Swift 2.1
• Converted to Swift 2.1 idioms where possible (`guard`/`defer`/`do` and `try`)

### CODE REVIEW

**Comment by harlanhaskins** [comment]
@practicalswift Here's an issue:

```
Pythonic-test.swift:1012:18: error: ambiguous use of 'zip'
    var zipped = zip([3, 4], [9, 16])
                 ^
Swift.zip:4:13: note: found this candidate
public func zip<Sequence1 : SequenceType, Sequence2 : SequenceType>(sequence1: Sequence1, _ sequence2: Sequence2) -> Zip2Sequence<Sequence1, Sequence2>
            ^
Pythonic.zip:1:13: note: found this candidate
public func zip<S1 : SequenceType, S2 : SequenceType>(s1: S1, _ s2: S2) -> [(S1.Generator.Element, S2.Generator.Element)]
```

How can we transparently disambiguate these?

**Comment by practicalswift** [comment]
Wow! Thanks for an excellent contribution. I did some work myself which is now in the tree: https://github.com/practicalswift/Pythonic.swift/commit/09556ee5a40aa4c13ba77f1595e9a87dec74e908

However, I think there is room for parts of your PR as well - some of your solutions are simply cleaner :-)

Would you mind pulling master and creating a new PR with the subset of your changes that you feel still should be in? That would be awesome!

**Comment by harlanhaskins** [comment]
What do you think about the zip case? Should we just get rid of the Zip that returns a list of tuples instead of a `CollectionType`?

**Comment by harlanhaskins** [comment]
Thanks for the merge! I still think we should address the zip function though. Right now, the tests don't compile...

**Comment by practicalswift** [comment]
Yes, let's remove zip :-)

**Comment by practicalswift** [comment]
Hi, it looks like your change set broke the tests for .pop (assert(mutableArray.pop() == 3) etc.) - do you know why? :-)

**Comment by practicalswift** [comment]
All tests are passing now after the latest commit :-)

**Comment by harlanhaskins** [comment]
Yep! I was just about to say that. I forgot to flip the logic when I switched to guard. D'oh! Glad it's working.

**Comment by practicalswift** [comment]
Thanks for a great contribution!

I'd love to see more contributions from you in the future if you are interested! :-)

**Pull request merged**
